config/routes.rb
Rails.application.routes.draw do


  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
  }
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope module: :public do
    root :to => "homes#top"
    get 'items/index'
    get 'about' =>  'homes#about'
    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :update] do
      collection do
        get :unsubscribe
        patch :withdraw
      end
    end
    # get 'customers/unsubscribe' => 'public/customers#unsubscribe'
    # patch 'customers/withdraw' => 'public/customers#withdraw'
    delete 'cart_items/destory_all' => 'cart_items#destroy_all'
    resources :cart_items, except: [:new,:show,:edit]
    get 'orders/complete' => 'orders#complete'
    post 'orders/confirm' => 'orders#confirm'
    resources :orders, only: [:new, :create, :index, :show]
    resources :adresses, except: [:new, :show]
  end
    namespace :admin do
      root :to => 'homes#top'
      resources :items, except: [:destroy]
      resources :customers, except: [:new, :destroy, :create]
      resources :genres, except: [:new, :destroy, :show]
      resources :order_items, only: [:show, :edit, :update]
      resources :orders, only: [:show, :update]
  end


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/adress.rb
class Adress < ApplicationRecord

    validates :postal_code, presence: true, length: { minimum: 7, maximum: 7 }
    validates :delivery, presence: true, length: { minimum: 5, maximum: 50 }
    validates :name, presence: true, length: { minimum: 2, maximum: 20 }
    # アソシエーション
    belongs_to :customer


    def full_delivery
         '〒' + self.postal_code + '　' + self.delivery + '　' + self.name
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item


  validates :quantity, presence: true


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

# 登録時のバリデーション、文字数、空白、入力文字の制限
  validates :fast_name, presence: true, length: { minimum: 1, maximum: 20 }
  validates :second_name, presence: true, length: { minimum: 1, maximum: 20 }
  validates :kana_fast_name, presence: true, length: { minimum: 1, maximum: 20 },
  format: {with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,message: "フリガナは、全角カタカナのみで入力して下さい"}
  validates :kana_second_name,presence: true, length: { minimum: 1, maximum: 20 },
  format: {with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,message: "フリガナは全角カタカナのみで入力して下さい"}
  validates :postal_code,presence: true , length: { minimum: 7, maximum: 7 }
  validates :address, presence: true, length: { minimum: 5, maximum: 50 }
  validates :telephone_number, presence: true, length: { minimum: 10, maximum: 12 }
  validates :email, presence: true

#アソシエーション
  has_many :adresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  # 退会機能
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
  
  def full_name
    self.fast_name + self.second_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  # ジャンルの名前の空白登録の制限
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  attachment :image
  belongs_to :genre
  has_many :order_items, dependent: :destroy
  validates :name, presence: true
  validates :text, presence: true
  validates :sub_price, presence: true
  validates :status, inclusion: { in: [true, false] }
end

app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to :customer
  has_many :order_items, dependent: :destroy
  
enum order_status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済:4}
def full_delivery
        " 〒 #{ self.postal_code } #{ self.address } #{ self.name } "
end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  # has_many :order
  belongs_to :order
  belongs_to :item



  enum make_status: { 着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3 }
  # enum make_status: { fuka: 0, mati: 1, cyuu: 2, kannryou: 3 } 

  validates :quantity, presence: true
  validates :main_price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/order_items_controller.rb
class Admin::OrderItemsController < ApplicationController
  before_action :authenticate_admin!

  def show
   @order = Order.find(params[:id])
   @order_items = @order.order_items
   # @order_item = @order.order_items.all
  end

  def update
      @orderItem = OrderItem.find(params[:id])
      @orderItem.update(order_item_params)
      redirect_to admin_order_path(@orderItem.order.id)
  end



   private

  def order_item_params
   params.require(:order_item).permit(:make_status)
  end

  def items_params
  params.require(:items).permit(:items, :sub_price)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fast_name, :second_name, :kana_fast_name, :kana_second_name, :postal_code, :address, :telephone_number, ])
  end

  def after_sign_in_path_for(resource)
   if resource.class.name == "Customer"
      root_path
   elsif resource.class.name == "Admin"
      admin_root_path
   end
  end


end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def create
  end
  
  def index
    @cart_items = current_customers
  end
  
  def update
  end
  
  def destroy
  end
  
  def destroy_all
  end
  
  
  private

  def cart_items_params
    params.require(:cart_items).permit(:quantity, :item_id)
  end
end

app/helpers/addreses_helper.rb
module AddresesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/order_items/edit.html.erb
<div class="container">
  <div class="row">
		<h1>注文履歴詳細</h1>
	</div>
	<div class="row">
<div class="row">
		<div class="col-md-10">
		  
		  <%= form_with model: @order, local: true, url: order_admins_order_path do |f| %>
		 <strong>購入者</strong> 
			<strong>配送先</strong> 〒
			<strong>支払い方法</strong> <br>
			<strong>注文ステータス</strong> 
							<%= f.submit '更新' %>
		  
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>商品名</th>
						<th>単価（税込）</th>
						<th>数量</th>
						<th>小計</th>
						<th>製作ステータス</th>
					</tr>
				</thead>
				<tbody>
					<% .each do |order_item| %>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>
								<%= f.submit '更新' %>
								<% end %><br>
							</td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>

app/views/admin/order_items/show.html.erb
<div class="container">
  <div class="row">
		<h1>注文履歴詳細</h1>
	</div>
		<div class="col-md-10">
		  
		<table>
			<tr>
				<td><strong>購入者</strong></td> 
				<td><%= @order.name %></td>
			</tr>
			<tr>
				<td><strong>注文日</strong></td>
				<td></td>
			</tr>
			
			<tr>
        <td><strong>配達先</strong></td>
        <td><%= '〒' + @order.postal_code %></td>
        <td><%= @order.address %></td>
      </tr>
      <tr>
      	<td></td>  
        <td><%= @order.name %></td>
    　</tr>
    　<tr>
    　	<td><strong>支払い方法</strong></td>
    　	<td>
        <% if @order.pay_selection == false %>
          クレジットカード
        <% else %>
          銀行振込
        <% end %>
      </td>
    　</tr>
    　<tr>
    　	<td><strong>注文ステータス</strong></td>
    　</tr>
		</table>  
		 
		  
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>商品名</th>
						<th>単価（税込)</th>
						<th>数量</th>
						<th>小計</th>
						<th>製作ステータス</th>
					</tr>
				</thead>
				<tbody>
					<% @order_item.each do |order_item| %>
						<tr>
							<td></td>
							<td> <%= order_item.quantity %></td>
							<td></td>
							<td></td>
							<td>
								<%= f.select :make_status, [['1', 0], ['2', 1], ['3', 2],['4', 3]] %> %>
							</td>
							<td><%= f.submit '更新' %>
								<br></td>
						</tr>
					<% end %>
				</tbody>
			</table>
			   <div class="col-1"></div>
        <table class="table col-3 table-borderless">
          <tr>
            <td >商品合計</th>
            <td <%=  %>円</td>
          </tr>
          <tr>
            <td >送料</td>
            <td ><%=  %></td>
          </tr>  
          <tr>
            <td >請求金額合計</td>
            <td ><%=  %>円</td>
          </tr>
        </table>
      </div>
</div>