config/routes.rb
Rails.application.routes.draw do


  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
  }
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope module: :public do
    root :to => "homes#top"
    get 'items/index'
    get 'about' =>  'homes#about'
    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :update] do
      collection do
        get :unsubscribe
        patch :withdraw
      end
    end
    # get 'customers/unsubscribe' => 'public/customers#unsubscribe'
    # patch 'customers/withdraw' => 'public/customers#withdraw'
    delete 'cart_items/destory_all' => 'cart_items#destroy_all'
    resources :cart_items, except: [:new,:show,:edit]
    get 'orders/complete' => 'orders#complete'
    post 'orders/confirm' => 'orders#confirm'
    resources :orders, only: [:new, :create, :index, :show]
    resources :adresses, except: [:new, :show]
  end
    namespace :admin do
      root :to => 'homes#top'
      resources :items, except: [:destroy]
      resources :customers, except: [:new, :destroy, :create]
      resources :genres, except: [:new, :destroy, :show]
      resources :order_items, only: [:show, :edit, :update]
      resources :orders, only: [:show, :update]
  end


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

# 登録時のバリデーション、文字数、空白、入力文字の制限
  validates :fast_name, presence: true, length: { minimum: 1, maximum: 20 }
  validates :second_name, presence: true, length: { minimum: 1, maximum: 20 }
  validates :kana_fast_name, presence: true, length: { minimum: 1, maximum: 20 },
  format: {with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,message: "フリガナは、全角カタカナのみで入力して下さい"}
  validates :kana_second_name,presence: true, length: { minimum: 1, maximum: 20 },
  format: {with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,message: "フリガナは全角カタカナのみで入力して下さい"}
  validates :postal_code,presence: true , length: { minimum: 7, maximum: 7 }
  validates :address, presence: true, length: { minimum: 5, maximum: 50 }
  validates :telephone_number, presence: true, length: { minimum: 10, maximum: 12 }
  validates :email, presence: true

#アソシエーション
  has_many :adresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  # 退会機能
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
  
  def full_name
    self.fast_name + self.second_name
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
     redirect_to admin_customer_path(@customer)
    else
     render :edit
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:fast_name, :second_name, :kana_fast_name, :kana_second_name, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController

  before_action :reject_customer, only: [:create]
  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false))
        flash[:error] = "退会済みです。"
        redirect_to new_customer_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/customers/edit.html.erb
    <div class="container">
        <!--エラーメッセージ表示-->
        <%= render 'public/error.msg', object: @customer %>


            <div class= "my-3">
            <h3><%= (@customer.fast_name + @customer.second_name) %> の会員情報</h3>
            </div>
            <%= form_with model:@customer, url: admin_customer_path(@customer), local:true do |f| %>
            <table class="form">
                <tbody>
                    <tr class="form-group row">
                       <td class="col-md-3"><%= f.label :会員ID %></td>
                       <td class="col-md-4"><%= f.label @customer.id %></td>
                    </tr>
                    <!--.form-inlineで中にmargin書き込む？？-->
                    <tr class="form-group row">
                        <td class="col-md-3"><%= f.label :氏名 %></td>
                        <td class="col-md-4"><%= f.text_field :fast_name, class: "form-control" %></td>
                        <td class="col-md-4"><%= f.text_field :second_name, class: "form-control" %></td>
                    </tr>
                    <tr class="form-group row">
                        <td class="col-md-3"><%= f.label :フリガナ %></td>
                        <td class="col-md-4"><%= f.text_field :kana_fast_name, class: "form-control" %></td>
                        <td class="col-md-4"><%= f.text_field :kana_second_name, class: "form-control" %></td>
                    </tr>
                    <tr class="form-group row">
                        <td class="col-md-3"><%= f.label :郵便番号 %></td>
                        <td class="col-md-4"><%= f.text_field :postal_code, class: "form-control" %></td>
                    </tr>
                    <tr class="form-group row">
                        <td class="col-md-3"><%= f.label :住所 %></td>
                        <td class="col-md-9"><%= f.text_field :address, class: "form-control" %></td>
                    </tr>
                    <tr class="form-group row">
                        <td class="col-md-3"><%= f.label :電話番号 %></td>
                        <td class="col-md-4"><%= f.text_field :telephone_number, class: "form-control" %></td>
                    </tr>
                    <tr class="form-group row">
                        <td class="col-md-3"><%= f.label :メールアドレス %></td>
                        <td class="col-md-4"><%= f.text_field :email, class: "form-control" %></td>
                    </tr>
                    <tr class="form-group row">
                        <td class="col-md-3"><%= f.label :会員ステータス %></td>
                        <td class="form-check col-md-4">
                          <!--このラジオボタンが選択されていたら、:is_deletedカラムに:trueとデータを送る-->
                          <!--有効ラベルの方を押しても、ラジオボタンが選択されるようにvalue: trueで連動させる-->
                          <%= f.radio_button :is_deleted, :false %>
                          <%= f.label :is_deleted, '有効', value: false %>
                          <!--:is_deletedカラムに:falseとデータを送る-->
                          <%= f.radio_button :is_deleted, :true %>
                          <!--ラジオボタン:falseと連動させる-->
                          <%= f.label :is_deleted, '無効', value: true %>
                        </td>
                    </tr>
                </tbody>
            </table>
　　　　　　<!--送信ボタン-->
　　　　　　<div class="form_btn mb-3">
　　　　　　    <div class="col-md-4 offset-md-3">
　　　　　　        <%= f.submit '変更を保存',  class:"btn btn-success" %>
                </div>
            </div>
           <% end %>
      </div>
    </div>

app/views/admin/customers/index.html.erb
<div class = "container">
    <h3>会員一覧画面</h3>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer|%>
        <tr>
          <td><%= customer.id %></td>
          <td><%= link_to (customer.fast_name + customer.second_name ), admin_customer_path(customer.id) %></td>
          <td><%= customer.email %></td>
          <td>
            <!--もし@customerのis_deletedに入っているデータがtrueだったら？-->
            <!--有効と表示そうでない時は、無効と表示する-->
            <% if customer.is_deleted == false %>
              <p class="custome_validity">有効</p>
            <% else%>
              <p class="custome_Invalid">無効</p>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div class="row text-center">
      <%= paginate @customers, class: "paginate" %>
    </div>
  </div>

app/views/admin/customers/show.html.erb
    <div class="container">
      <h3><%= (@customer.fast_name + @customer.second_name) %>の会員詳細</h3>
      <table class="form">
        <tbody>
          <tr>
            <td class="col-md-3">会員ID</td>
            <td class="col-md-4"><%= @customer.id %></td>
          </tr>
          <tr>
            <td class="col-md-3">氏名</td>
            <td class="col-md-4"><%= (@customer.fast_name + @customer.second_name) %></td>
          </tr>
          <tr>
            <td class="col-md-3">フリガナ</td>
            <td class="col-md-4"><%= (@customer.kana_fast_name + @customer.kana_second_name) %></td>
          </tr>
          <tr>
            <td class="col-md-3">郵便番号</td>
            <td class="col-md-4"><%= @customer.postal_code %></td>
          </tr>
          <tr>
            <td class="col-md-3">住所</td>
            <td class="col-md-9"><%= @customer.address %></td>
          </tr>
          <tr>
            <td class="col-md-3">電話番号</td>
            <td class="col-md-4"><%= @customer.telephone_number %></td>
          </tr>
          <tr>
            <td class="col-md-3">メールアドレス</td>
            <td class="col-md-4"><%= @customer.email %></td>
          </tr>
          <tr>
            <td class="col-md-3">会員ステータス</td>
            <td class="col-md-4">
              <!--もし@customerのis_deletedに入っているデータがtrueだったら？-->
              <!--有効と表示そうでない時は、無効と表示する-->
              <% if @customer.is_deleted == false %>
               <p class="custome_validity">有効</p>
              <% else%>
               <p class="custome_Invalid">無効</p>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <div class="form_btn">
        <div class="row">
          <%= link_to "編集する", edit_admin_customer_path(@customer.id), class:"btn btn-success" %>
          <%= link_to "注文履歴一覧を見る", admin_root_path, class:"btn btn-primary" %>
        </div>
      </div>
    </div>