config/routes.rb
Rails.application.routes.draw do


  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
  }
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope module: :public do
    root :to => "homes#top"
    get 'items/index'
    get 'about' =>  'homes#about'
    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :update] do
      collection do
        get :unsubscribe
        patch :withdraw
      end
    end
    # get 'customers/unsubscribe' => 'public/customers#unsubscribe'
    # patch 'customers/withdraw' => 'public/customers#withdraw'
    delete 'cart_items/destory_all' => 'cart_items#destroy_all'
    resources :cart_items, except: [:new,:show,:edit]
    get 'orders/complete' => 'orders#complete'
    post 'orders/confirm' => 'orders#confirm'
    resources :orders, only: [:new, :create, :index, :show]
    resources :adresses, except: [:new, :show]
  end
    namespace :admin do
      root :to => 'homes#top'
      resources :items, except: [:destroy]
      resources :customers, except: [:new, :destroy, :create]
      resources :genres, except: [:new, :destroy, :show]
      resources :order_items, only: [:show, :edit, :update]
      resources :orders, only: [:show, :update]
  end


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/adress.rb
class Adress < ApplicationRecord

    validates :postal_code, presence: true, length: { minimum: 7, maximum: 7 }
    validates :delivery, presence: true, length: { minimum: 5, maximum: 50 }
    validates :name, presence: true, length: { minimum: 2, maximum: 20 }
    # アソシエーション
    belongs_to :customer


    def full_delivery
         '〒' + self.postal_code + '　' + self.delivery + '　' + self.name
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item


  validates :quantity, presence: true


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

# 登録時のバリデーション、文字数、空白、入力文字の制限
  validates :fast_name, presence: true, length: { minimum: 1, maximum: 20 }
  validates :second_name, presence: true, length: { minimum: 1, maximum: 20 }
  validates :kana_fast_name, presence: true, length: { minimum: 1, maximum: 20 },
  format: {with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,message: "フリガナは、全角カタカナのみで入力して下さい"}
  validates :kana_second_name,presence: true, length: { minimum: 1, maximum: 20 },
  format: {with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,message: "フリガナは全角カタカナのみで入力して下さい"}
  validates :postal_code,presence: true , length: { minimum: 7, maximum: 7 }
  validates :address, presence: true, length: { minimum: 5, maximum: 50 }
  validates :telephone_number, presence: true, length: { minimum: 10, maximum: 12 }
  validates :email, presence: true

#アソシエーション
  has_many :adresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  # 退会機能
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
  
  def full_name
    self.fast_name + self.second_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  # ジャンルの名前の空白登録の制限
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  attachment :image
  belongs_to :genre
  has_many :order_items, dependent: :destroy
  validates :name, presence: true
  validates :text, presence: true
  validates :sub_price, presence: true
  validates :status, inclusion: { in: [true, false] }
end

app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to :customer
  has_many :order_items, dependent: :destroy
  
enum order_status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済:4}
def full_delivery
        " 〒 #{ self.postal_code } #{ self.address } #{ self.name } "
end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  # has_many :order
  belongs_to :order
  belongs_to :item



  enum make_status: { 着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3 }
  # enum make_status: { fuka: 0, mati: 1, cyuu: 2, kannryou: 3 } 

  validates :quantity, presence: true
  validates :main_price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fast_name, :second_name, :kana_fast_name, :kana_second_name, :postal_code, :address, :telephone_number, ])
  end

  def after_sign_in_path_for(resource)
   if resource.class.name == "Customer"
      root_path
   elsif resource.class.name == "Admin"
      admin_root_path
   end
  end


end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def create
  end
  
  def index
    @cart_items = current_customers
  end
  
  def update
  end
  
  def destroy
  end
  
  def destroy_all
  end
  
  
  private

  def cart_items_params
    params.require(:cart_items).permit(:quantity, :item_id)
  end
end

app/helpers/addreses_helper.rb
module AddresesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "こちら", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "こちら", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('favicon.ico') %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar">
        <div class=container>
          <div class="navbar-brand"><%= image_tag "logo1.png"%></div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <!-- カスタマー側がログインしたら -->
              <% if customer_signed_in? %>
                <li><%=link_to'マイページ', customer_path(current_customer),class: 'nav-link' %></li>
                <li><%=link_to'商品一覧',items_path,class: 'nav-link' %></li>
                <li><%=link_to'カート', cart_items_path,class: 'nav-link' %></li>
                <li><%=link_to'ログアウト', destroy_customer_session_path, method: :delete, class: 'nav-link' %></li>
              <!-- 管理者側がログインしたら -->
              <% elsif admin_signed_in? %>
                <li><%=link_to'商品一覧', admin_items_path,class: 'nav-link' %></li>
                <li><%=link_to'会員一覧', admin_customers_path, class:'nav-link' %></li>
                <li><%=link_to'注文履歴一覧', admin_root_path, class: 'nav-link' %></li>
                <li><%=link_to'ジャンル一覧', admin_genres_path,class: 'nav-link' %></li>
                <li><%=link_to'ログアウト',  destroy_admin_session_path, method: :delete, class: 'nav-link' %></li>
              <% else %>
                <li><%=link_to'About', about_path, class: 'nav-link' %></li>
                <li><%=link_to'商品一覧', items_path, class: 'nav-link' %></li>
                <li><%=link_to'新規登録', new_customer_registration_path,class: 'nav-link' %></li>
                <li><%=link_to'ログイン', new_customer_session_path, class: 'nav-link' %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
    <%# deivseのフラッシュメッセージを表示 %>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% elsif alert %>
　    <p class="alert"><%= alert %></p>
  　<% end %>
    <%= yield %>
    </main>
    <footer class="footer">
      <div class="container text-center mt-3">
        <p><smal>&copy; nagano_cake.inc</smal></p>
      </div>
    </footer>
  </body>
</html>